using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Gu.Wpf.NumericInput.UITests")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Gu.Wpf.NumericInput.UITests")]
[assembly: AssemblyCopyright("Copyright ©  2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("03820c66-202b-4b6d-b9d5-e4f3267362c1")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: NUnit.Framework.LevelOfParallelism(1)]
